---
title: Spillane Makes
timezone: America/New_York
collections:
  pets:
    title: Pets
    output: true
    permalink: "/:collection/:path/"
  portfolio:
    title: Portfolio
    output: true
    permalink: "/:collection/:path/"
  posts:
    title: Posts
    output: true
  recipes:
    title: Recipes
    output: true
    permalink: "/:collection/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    share: true
    related: true
- scope:
    path: _pages
    type: pages
  values:
    layout: single
    author_profile: true
- scope:
    path: ''
    type: recipes
  values:
    layout: single
    author_profile: true
    share: true
- scope:
    path: ''
    type: pets
  values:
    layout: single
    author_profile: true
    share: true
- scope:
    path: ''
    type: portfolio
  values:
    layout: single
    author_profile: false
    share: true
minimal_mistakes_skin: contrast
locale: en-US
title_separator: "|"
subtitle: Maker/Engineering Portfolio
name: Dan Spillane
description: Additive Engineering Design Graduate Researcher
url: https://SpillaneMakes.com
baseurl: ''
repository: SpillaneMakes/SpillaneMakes.github.io
teaser: "/assets/images/Voxel_Lion.jpg"
logo: "/assets/images/DSLogo.png"
masthead_title: 
words_per_minute: 200
comments:
  provider: 'false'
  disqus:
    shortname: 
  discourse:
    server: 
  facebook:
    appid: 
    num_posts: 
    colorscheme: 
  utterances:
    theme: 
    issue_term: 
reCaptcha:
  siteKey: 
  secret: 
atom_feed:
  path: 
search: true
search_full_content: true
search_provider: lunr
algolia:
  application_id: QB6HVGBSBA
  index_name: minimal_mistakes
  search_only_api_key: 9d5014e5bbc77372547bce778dfa5663
  powered_by: true
  files_to_exclude: 
google_site_verification: 
bing_site_verification: 
yandex_site_verification: 
naver_site_verification: 
twitter:
  username: SpillaneMakes
facebook:
  username: 
  app_id: 
  publisher: 
og_image: "/assets/images/site-logo.png"
social:
  type: Person
  name: Dan Spillane
  links:
  - https://twitter.com/SpillaneMakes
  - https://github.com/SpillaneMakes
analytics:
  provider: google-universal
  google:
    tracking_id: UA-2011187-3
    anonymize_ip: true
author:
  name: Dan Spillane
  avatar: "/assets/images/SpillaneProfPic.jpg"
  bio: 
  location: State College, PA
  links:
  - label: Email
    icon: fas fa-fw fa-envelope-square
    url: Dan@SpillaneMakes.com
  - label: Resume
    icon: fas fa-fw fa-link
    url: https://DanSpillane.co
  - label: Twitter
    icon: fab fa-fw fa-twitter-square
    url: https://twitter.com/SpillaneMakes
  - label: GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/SpillaneMakes
  - label: Instagram
    icon: fab fa-fw fa-instagram
    url: https://instagram.com/SpillaneMakes
footer:
  links:
  - label: Email
    icon: fas fa-fw fa-envelope-square
    url: "/contact_me/"
  - label: Resume
    icon: fas fa-fw fa-link
    url: https://DanSpillane.co
  - label: Twitter
    icon: fab fa-fw fa-twitter-square
    url: https://twitter.com/SpillaneMakes
  - label: GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/SpillaneMakes
  - label: Instagram
    icon: fab fa-fw fa-instagram
    url: https://instagram.com/SpillaneMakes
include:
- ".htaccess"
- _pages
exclude:
- "*.sublime-project"
- "*.sublime-workspace"
- vendor
- ".asset-cache"
- ".bundle"
- ".jekyll-assets-cache"
- ".sass-cache"
- assets/js/plugins
- assets/js/_main.js
- assets/js/vendor
- Capfile
- CHANGELOG
- config
- Gemfile
- Gruntfile.js
- gulpfile.js
- LICENSE
- log
- node_modules
- package.json
- Rakefile
- README
- tmp
keep_files:
- ".git"
- ".svn"
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
strict_front_matter: true
liquid:
  error_mode: strict
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:categories/:title/"
paginate: 7
paginate_path: "/page:num/"
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-include-cache
whitelist:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-include-cache
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
compress_html:
  clippings: all
  ignore:
    envs: development
